/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import controlador.Ctrl_Categoria;
import java.awt.Dimension;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Categoria;
import validadores.Validadores;

/**
 *
 * @author Emilio
 */
public class InterHabilitarCliente extends javax.swing.JInternalFrame {
public Validadores validadores = new Validadores ();
    /**
     * Creates new form InterUsuario
     */
    public InterHabilitarCliente() {
        initComponents();
        this.setSize(new Dimension(400, 200));
        this.setTitle("Nueva Categoria");
        String[] opciones = {"Habilitar", "Deshabilitar"};
        cbOpciones.setModel(new DefaultComboBoxModel<>(opciones));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbOpciones = new javax.swing.JComboBox<>();
        txt_habilitarbuscar = new javax.swing.JTextField();
        jButton_Habilitar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Opcion: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Habilitar/Deshabilitar Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Buscar cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, -1));

        cbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 170, 20));

        txt_habilitarbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_habilitarbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txt_habilitarbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, -1));

        jButton_Habilitar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Habilitar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_Habilitar.setText("Guardar");
        jButton_Habilitar.setToolTipText("");
        jButton_Habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HabilitarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Habilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.png"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HabilitarActionPerformed
String cedula = txt_habilitarbuscar.getText().trim();
    String opcionSeleccionada = (String) cbOpciones.getSelectedItem(); // Opción seleccionada en el JComboBox

    String mensajeError = Validadores.validarClienteHabilitado(cedula, opcionSeleccionada);
    if (mensajeError != null) {
        JOptionPane.showMessageDialog(this, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        Connection conexion = Conexion.conectar();
        PreparedStatement ps = null;
        try {
            String consulta;
            if (opcionSeleccionada.equals("Habilitar")) {
                consulta = "UPDATE tb_cliente SET estado = 1 WHERE cedula = ?";
            } else {
                consulta = "UPDATE tb_cliente SET estado = 0 WHERE cedula = ?";
            }
            ps = conexion.prepareStatement(consulta);
            ps.setString(1, cedula);
            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Operación realizada con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar el estado del cliente", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al ejecutar la consulta: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (ps != null) ps.close();
                if (conexion != null) conexion.close();
            } catch (SQLException e) {
                System.out.println("Error al cerrar recursos: " + e);
            }
        }
    }

        
    }//GEN-LAST:event_jButton_HabilitarActionPerformed

    private void txt_habilitarbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_habilitarbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_habilitarbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbOpciones;
    private javax.swing.JButton jButton_Habilitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txt_habilitarbuscar;
    // End of variables declaration//GEN-END:variables

}
