/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.Ctrl_Categoria;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Categoria;

/**
 *
 * @author Emilio
 */
public class InterHabilitarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterUsuario
     */
    public InterHabilitarCliente() {
        initComponents();
        this.setSize(new Dimension(400, 200));
        this.setTitle("Nueva Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_habilitarbuscar = new javax.swing.JTextField();
        jButton_Habilitar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Habilitar Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Buscar cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));

        txt_habilitarbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_habilitarbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txt_habilitarbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, -1));

        jButton_Habilitar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Habilitar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_Habilitar.setText("Habilitar");
        jButton_Habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HabilitarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Habilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.png"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HabilitarActionPerformed

        Categoria categoria = new Categoria();
        Ctrl_Categoria controlCategoria = new Ctrl_Categoria();

        //validamos camoos vacios
        if (txt_habilitarbuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete  todos los campos");
        } else {
            if (!controlCategoria.existeCategoria(txt_habilitarbuscar.getText().trim())) {
                categoria.setDescripcion(txt_habilitarbuscar.getText().trim());
                categoria.setEstado(1);
                if (controlCategoria.guardar(categoria)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "La Categoria ya esta registrada en la Base de Datos");
            }
        }
        //limpiar campo
        txt_habilitarbuscar.setText("");
    }//GEN-LAST:event_jButton_HabilitarActionPerformed

    private void txt_habilitarbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_habilitarbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_habilitarbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Habilitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txt_habilitarbuscar;
    // End of variables declaration//GEN-END:variables

}
